locale = "en"
label = "English"
weight = 1
title = "hcrockstar"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Personal blog site"

[params.author]
  name = "hcrockstar"
  email = "henrycrodriguez@hcrockstar.com"
  image = "img/blowfish_logo.png"
  headline = "Personal blog site"
  bio = "Personal blog site"
  links = [
    { x-twitter = "https://twitter.com/iamHCRockstar" }
  ]